### PR TITLE
[WIP] Crimson/Warped Things Implementation

### PR DESCRIPTION
**Pull request by good777LUCKY**
<**Crimson/Warped Things Implementation**>

> Implementation:
- [x] Crimson/Warped Stem
- [x] Crimson/Warped Stripped Stem
- [x] Crimson/Warped Hyphae
- [x] Crimson/Warped Stripped Hyphae
- [x] Crimson/Warped Planks
- [x] Crimson/Warped Door
- [x] Crimson/Warped Trapdoor
- [x] Crimson/Warped Fence
- [x] Crimson/Warped Fence Gate
- [x] Crimson/Warped Button
- [x] Crimson/Warped Pressure Plate
- [x] Crimson/Warped Sign Post
- [x] Crimson/Warped Wall Sign
- [x] Crimson/Warped Stairs
- [x] Crimson/Warped Slap
- [x] Crimson/Warped Double Slaps

> TODO:
- [ ] Add all blocks color
- [ ] Correct all resistance
- [ ] Add correct face(damage) to stem
- [ ] Add correct damage to hyphae

### CODE REVIEW

**Comment by good777LUCKY** [comment]
@joserobjr Can you correct Block ID Names again? I think something is conflicting.

**Comment by joserobjr** [comment]
sure, in few minutes

**Comment by Jl1mbo** [comment]
Should I fix it?

**Comment by good777LUCKY** [comment]
> Should I fix it?

Yes, thank you

**Comment by Jl1mbo** [comment]
What is this branch?

**Comment by good777LUCKY** [comment]
> What is this branch?

good777LUCKY:New-Implementation

**Comment by joserobjr** [comment]
I'm fixing

**Comment by good777LUCKY** [comment]
Thank you

**Comment by Jl1mbo** [comment]
How do you know that handler or resistance is 2 or 3?

**Comment by good777LUCKY** [comment]
> How do you know that handler or resistance is 2 or 3?

I don't know correct data, so I should update with correct data.

**Comment by good777LUCKY** [comment]
Do you know correct data for it?

**Comment by good777LUCKY** [comment]
@joserobjr Is block resistance is explode resistance?

**Comment by good777LUCKY** [comment]
TODO: Fix crimson/warped stem direction

**Comment by joserobjr** [comment]
Thank you for your contribution! I'm going to finish what is needed in the warped-crimson branch.

**Comment by good777LUCKY** [comment]
> Thank you for your contribution! I'm going to finish what is needed in the warped-crimson branch.

Thank you!

**Pull request merged**
