### PR TITLE
Correction of efficiency in Block.java

### PR DESCRIPTION
**Pull request by Egor-Ermolaev**
In the article about breaking blocks (https://minecraft.fandom.com/wiki/Breaking ) exponentiation is used to calculate the speed. In java, exponentiation is achieved thanks to Math.pow(). This solves all the problems with breaking blocks with a pickaxe with enchantment efficiency.

### CODE REVIEW

**Comment by Egor-Ermolaev** [comment]
image
In some cases, a faster pickaxe digs slower, which is strange.

**Comment by hteppl** [comment]
With these changes, speedMultiplier matches the data from Wikipedia. The formula is correct.

image

image
https://minecraft.fandom.com/wiki/Breaking

**Review by roridev — APPROVED** [review]

**Comment by roridev** [comment]
oh my. aight thats approved. thanks for spotting this one.

**Comment by Superzock3003** [comment]
Doesn't this line have the same error? https://github.com/PowerNukkit/PowerNukkit/blob/10a33298453d733172c7d21626606f826b96f9ad/src/main/java/cn/nukkit/block/Block.java#L1358

**Comment by IWareQ** [comment]
> Doesn't this line have the same error? https://github.com/PowerNukkit/PowerNukkit/blob/10a33298453d733172c7d21626606f826b96f9ad/src/main/java/cn/nukkit/block/Block.java#L1358

No

**Comment by roridev** [comment]
> Doesn't this line have the same error?
> 
> https://github.com/PowerNukkit/PowerNukkit/blob/10a33298453d733172c7d21626606f826b96f9ad/src/main/java/cn/nukkit/block/Block.java#L1358

It could. Unless the formula expects you to XOR the values instead of using exponentiation. The issue would be the exact same as this one.

**Pull request merged**
