### PR TITLE
Allow nether huge fungi to grow from their fungi saplings

### PR DESCRIPTION
**Pull request by FlamingKnight**
This PR lets players bonemeal nether fungi to grow into their huge fungi trees, you can also remove the sign code below since that was from a while ago and I don't know how to remove it from this PR, here are some examples of what the trees look like when generated!
Minecraft 7_1_2021 8_09_29 PM
Minecraft 7_1_2021 8_11_33 PM
Minecraft 7_1_2021 8_09_50 PM

### CODE REVIEW

**Comment by roridev** [comment]
If you don't know how to extract the commit that added that feature into another branch I can do that for you and make another pr with your additions. This history is just weird.

**Comment by FlamingKnight** [comment]
I actually I think I can do that quickly, I wasn't too sure what I was doing before with branches a lot

**Comment by roridev** [comment]
Ah thanks.

**Comment by FlamingKnight** [comment]
Alright @roridev did it in PR #1189 , thanks!

**Pull request closed without merging**
