### PR TITLE
Update ProtocolInfo.java

### PR DESCRIPTION
**Pull request by Lycol50**
bump to protocol 431

### CODE REVIEW

**Comment by Lycol50** [comment]
this is from 210-protocol branch

**Comment by GoodLucky777** [comment]
BinaryStream(item) need to be updated because it changed in this update

**Comment by Jl1mbo** [comment]
copy to NukkutX

**Comment by Lycol50** [comment]
> BinaryStream(item) need to be updated because it changed in this update

ah yes, because they added new items.

**Comment by Lycol50** [comment]
check this PR from CloudburstNK
https://github.com/CloudburstMC/Nukkit/pull/1820/files

**Comment by Gabriel8579** [comment]
Doing this at #1040 thank you!

**Pull request closed without merging**
