### PR TITLE
Fix support rules for a lot of blocks, some block attributes, bounding boxes and rewrite snow_layer

### LINKED ISSUE #482: Some chunks are not loaded
# 🐞 I found a bug
I had this bug in the latest bleeding build

### 📋 Debug information
* Debug link: https://debugpaste.powernukkit.org/pastes/mozajeveki

### 💢 Crash Dump, Stack Trace and Other Files
```java
[ERROR] ワールド "world" をチェックすることができませんでした: cn.nukkit.blockproperty.exception.InvalidBlockPropertyMetaException: Property: new_leaf_type. Current Meta: 11, Invalid Meta: 3
        at cn.nukkit.blockproperty.BlockProperty.validateMeta(BlockProperty.java:268)
        at cn.nukkit.blockstate.IntMutableBlockState.validate(IntMutableBlockState.java:82)
        at cn.nukkit.blockstate.IntMutableBlockState.setDataStorage(IntMutableBlockState.java:63)
        at cn.nukkit.block.Block.setDataStorage(Block.java:1536)
        at cn.nukkit.blockstate.IBlockState.getBlock(IBlockState.java:119)
        at cn.nukkit.level.Level.getBlock(Level.java:1577)
        at cn.nukkit.level.Level.getBlock(Level.java:1551)
        at cn.nukkit.block.Block.getSideAtLayer(Block.java:1178)
        at cn.nukkit.block.Block.getSide(Block.java:1169)
        at cn.nukkit.block.BlockLeaves.findLog(BlockLeaves.java:232)
        at cn.nukkit.block.BlockLeaves.findLog(BlockLeaves.java:232)
        at cn.nukkit.block.BlockLeaves.findLog(BlockLeaves.java:232)
        at cn.nukkit.block.BlockLeaves.findLog(BlockLeaves.java:232)
        at cn.nukkit.block.BlockLeaves.findLog(BlockLeaves.java:232)
        at cn.nukkit.block.BlockLeaves.findLog(BlockLeaves.java:232)
        at cn.nukkit.block.BlockLeaves.findLog(BlockLeaves.java:232)
        at cn.nukkit.block.BlockLeaves.onUpdate(BlockLeaves.java:182)
        at cn.nukkit.level.Level.tickChunks(Level.java:1163)
        at cn.nukkit.level.Level.doTick(Level.java:850)
        at cn.nukkit.Server.checkTickUpdates(Server.java:1208)
        at cn.nukkit.Server.tick(Server.java:1290)
        at cn.nukkit.Server.tickProcessor(Server.java:1062)
        at cn.nukkit.Server.start(Server.java:1030)
        at cn.nukkit.Server.<init>(Server.java:691)
        at cn.nukkit.Nukkit.main(Nukkit.java:120)
Caused by: java.lang.IndexOutOfBoundsException: index (3) must be less than size (2)
        at com.google.common.base.Preconditions.checkElementIndex(Preconditions.java:1348)
        at com.google.common.base.Preconditions.checkElementIndex(Preconditions.java:1330)
        at cn.nukkit.blockproperty.ArrayBlockProperty.validateMeta(ArrayBlockProperty.java:139)
        at cn.nukkit.blockproperty.BlockProperty.validateMeta(BlockProperty.java:266)
        ... 24 more

18:34:46 [ERROR] ワールド "world" をチェックすることができませんでした: cn.nukkit.blockproperty.exception.InvalidBlockPropertyMetaException: Property: new_leaf_type. Current Meta: 11, Invalid Meta: 3
        at cn.nukkit.blockproperty.BlockProperty.validateMeta(BlockProperty.java:268)
        at cn.nukkit.blockstate.IntMutableBlockState.validate(IntMutableBlockState.java:82)
        at cn.nukkit.blockstate.IntMutableBlockState.setDataStorage(IntMutableBlockState.java:63)
        at cn.nukkit.block.Block.setDataStorage(Block.java:1536)
        at cn.nukkit.blockstate.IBlockState.getBlock(IBlockState.java:119)
        at cn.nukkit.level.Level.getBlock(Level.java:1577)
        at cn.nukkit.level.Level.getBlock(Level.java:1551)
        at cn.nukkit.block.Block.getSideAtLayer(Block.java:1178)
        at cn.nukkit.block.Block.getSide(Block.java:1169)
        at cn.nukkit.block.BlockLeaves.findLog(BlockLeaves.java:232)
        at cn.nukkit.block.BlockLeaves.findLog(BlockLeaves.java:232)
        at cn.nukkit.block.BlockLeaves.onUpdate(BlockLeaves.java:182)
        at cn.nukkit.level.Level.tickChunks(Level.java:1163)
        at cn.nukkit.level.Level.doTick(Level.java:850)
        at cn.nukkit.Server.checkTickUpdates(Server.java:1208)
        at cn.nukkit.Server.tick(Server.java:1290)
        at cn.nukkit.Server.tickProcessor(Server.java:1062)
        at cn.nukkit.Server.start(Server.java:1030)
        at cn.nukkit.Server.<init>(Server.java:691)
        at cn.nukkit.Nukkit.main(Nukkit.java:120)
Caused by: java.lang.IndexOutOfBoundsException: index (3) must be less than size (2)
        at com.google.common.base.Preconditions.checkElementIndex(Preconditions.java:1348)
        at com.google.common.base.Preconditions.checkElementIndex(Preconditions.java:1330)
        at cn.nukkit.blockproperty.ArrayBlockProperty.validateMeta(ArrayBlockProperty.java:139)
        at cn.nukkit.blockproperty.BlockProperty.validateMeta(BlockProperty.java:266)
        ... 19 more
```

### LINKED ISSUE #496: Client spam bug may affect performance
# 🐞 I found a bug

### 📸 Screenshots / Videos

https://youtu.be/xKNOX8XSziw

### ▶ Steps to Reproduce

1. Place a lever
2. Put any non-usable item in your hands
3. Hold sneaky (shift)
4. Hold use (right click) in the lever

Tested with keyboard+mouse and with joystick

### ✔ Expected Behavior

Switch the lever slowly

### ❌ Actual Behavior

The client auto-jitter-click the lever (and everything else)

### 📋 Debug information

* PowerNukkit version: 1.4.0.0-PN-SNAPSHOT
* Debug link: https://debugpaste.powernukkit.org/pastes/iyagikuzeh

### 💬 Anything else we should know?

Related to #287 and #366

### LINKED ISSUE #506: Flying up + Breaking blocks above = rubberband
# 🐞 I found a bug

### 📸 Screenshots / Videos

https://youtu.be/oiYwvlwgdr8

### ▶ Steps to Reproduce

1. Go to an underground cave
2. Get in creative
3. Try to leave it flying up and breaking blocks above you
4. Get rubber-banded a lot

### ✔ Expected Behavior

No rubber-bands, break and leave the blocks normally

### ❌ Actual Behavior

You get stuck in the cave

### 📋 Debug information

* PowerNukkit version: 1.4.0.0-PN at 7897702

### 💢 Crash Dump, Stack Trace and Other Files

Nothing is logged as INFO+

### PR DESCRIPTION
**Pull request by LoboMetalurgico**
This pull will fix the #283 and #372 issues.

Before we can merge this, we need to complete this list:

### TODO:

- [x] Implement torch on this fix

### Fix

- [x] Any wall side is solid
- [x] Can't be placed on slab at the top half of the block
- [x] Can't be placed on top of upside-down stairs
- [x] Levers and Buttons now can be placed in any solid block (this includes cocoa, leaves and other wrong blocks)

## Placement fix
- [x] bed
- [x] bell
- [x] buttons
- [x] doors
- [x] rails
- [x] ladders
- [x] lever
- [x] saplings
- [x] torches
- [x] turtle eggs
- [x] Dead bush
- [x] Double plant
- [x] Fence gate
- [x] Flowers
- [x] Flowerpot
- [x] Ladder
- [x] Lantern
- [x] Lever
- [x] Pressure plates
- [x] Rails
- [x] Redstone repeater
- [x] Redstone comparator
- [x] Redstone wire
- [x] Saplings
- [x] Sweetberry bush
- [x] Tallgrass
- [x] Torches
- [x] Turtle egg

## Bounding box fix
- [x] Anvil
- [x] Chain
- [x] Enchanting table
- [x] Soul sand
- [x] Stonecutter block

## Attribute fix
- [x] Air
- [x] Cauldron
- [x] Carpet
- [x] Bubble collumn
- [x] Enchanting table
- [x] Farmland
- [x] Grass path
- [x] Hopper
- [x] Liquids
- [x] Piston head
- [x] Scaffolding
- [x] Signs
- [x] Skulls
- [x] Slabs
- [x] Stairs
- [x] Glass panes
- [x] Iron bars
- [x] Shulker boxes
- [x] Vine
- [x]  Walls

## Implementation
- [x] Snow layer
- [x] Fix #496 (revert #403)
- [x] Fix #482
- [x] Fix #506
- [x] Add `Biome.isDry()`
- [x] Add new constructor to `ArrayBlockProperty` that allows to define a custom `String[]` of serialized property values
- [x] Chunk content version increased to 10

### CODE REVIEW

**Comment by joserobjr** [comment]
Might also fix #372

**Comment by joserobjr** [comment]
I also found the bedrock edition torch placement rules documented in the wiki. It's the page document colored torches but might be the same rules for all torches.
https://minecraft.gamepedia.com/Colored_Torch#Placement

**Comment by LoboMetalurgico** [comment]
Thank you! I will work on them too.

**Comment by joserobjr** [comment]
Test worlds
[KRk3XyvFEAA=.zip](https://github.com/PowerNukkit/PowerNukkit/files/5091656/KRk3XyvFEAA.zip)

[worlds.zip](https://github.com/PowerNukkit/PowerNukkit/files/5091663/worlds.zip)

**Comment by MrRazamataz** [comment]
Does this fix not being able to place rails on hoppers?

**Comment by good777LUCKY** [comment]
> Does this fix not being able to place rails on hoppers?

It was fixed in #432

**Comment by MrRazamataz** [comment]
> > Does this fix not being able to place rails on hoppers?
> 
> It was fixed in #432 

Is this only in bleeding branch at the moment?

**Comment by good777LUCKY** [comment]
> > > Does this fix not being able to place rails on hoppers?
> > 
> > 
> > It was fixed in #432
> 
> Is this only in bleeding branch at the moment?

yes

**Comment by MrRazamataz** [comment]
> > > > Does this fix not being able to place rails on hoppers?
> > > 
> > > 
> > > It was fixed in #432
> > 
> > Is this only in bleeding branch at the moment?
> 
> yes

Yes ok that makes sense. Can't wait!!!!!!

**Pull request merged**
