### PR TITLE
Patch the fix for PowerNukkit#887

### PR DESCRIPTION
**Pull request by KCodeYT**

### CODE REVIEW

**Comment by AntonPPDS** [comment]
It may be better to execute `tryEncode()` before cloning, since if the same packet instance is sent to different players, it will already have an encoded buffer.

**Comment by GoodLucky777** [comment]
I tested with
```java
packet.tryEncode();
packet = packet.clone();
session.outbound.offer(packet);
```
it was working great with plugins without disconnect issue

**Comment by RORIdev** [comment]
> I tested with
> 
> ```java
> packet.tryEncode();
> packet = packet.clone();
> session.outbound.offer(packet);
> ```
> 
> it was working great with plugins without disconnect issue

If thats all it takes to fix the disconnect bug, can @KCodeYT implement these changes so I can test and merge this pr?
Or someone else could make another PR with the same fix, since this seems critical.

**Comment by KCodeYT** [comment]
> > I tested with
> > ```java
> > packet.tryEncode();
> > packet = packet.clone();
> > session.outbound.offer(packet);
> > ```
> > 
> > 
> > it was working great with plugins without disconnect issue
> 
> If thats all it takes to fix the disconnect bug, can @KCodeYT implement these changes so I can test and merge this pr?
> Or someone else could make another PR with the same fix, since this seems critical.

Done

**Comment by RORIdev** [comment]
Good. I'll test it and merge.

**Comment by joserobjr** [comment]
Thank you for the PR!
I've just merged the PR #940 that fixes the same issue, so I'm closing as duplicated. Thank you anyway 👍

**Review by joserobjr — APPROVED** [review]

**Pull request closed without merging**
