### PR TITLE
Fix `candles` branch test error and some improvement

### PR DESCRIPTION
**Pull request by GoodLucky777**
Fix [PowerNukkit:candles](https://github.com/PowerNukkit/PowerNukkit/tree/candles) branch test error because of resources and some improvement

- Add
  - Glow Frame (Item)
  - A few item ids
- Fix
  - Resource files
  - Test
  - Creative inventory doesn't show few items
- Change
  - ItemRawMaterial extend Item (now legacy id can be found in [Minecraft Wiki](https://minecraft.fandom.com/wiki/Bedrock_Edition_data_values#Item_IDs))
- Improve
  - Don't show unknown recipe and creative item error for not implemented things

### CODE REVIEW

**Comment by LoboMetalurgico** [comment]
Can you rebase to #1223 (branch candles)? It has many fixes, in addition to the latest bleeding merges (although theoretically it's just to implement the candles, by my mistake it turned into a super patch)

**Comment by LoboMetalurgico** [comment]
Can you rebase to #1223 (branch candles)? It has many fixes, in addition to the latest bleeding merges (although theoretically it's just to implement the candles, by my mistake it turned into a super patch)

**Comment by LoboMetalurgico** [comment]
I changed the base, but there were conflicts in `runtime_item_ids.json`. If we manage to resolve this conflict, we will finally be able to do one last review, confirm that everything is ok and release a lot of new features.

**Comment by GoodLucky777** [comment]
Ready to be reviewed

**Review by LoboMetalurgico — APPROVED** [review]
Thank you!

**Pull request merged**
