### PR TITLE
Add Amethyst Shard

### PR DESCRIPTION
**Pull request by GoodLucky777**
Add Amethyst Shard (Item)

### CODE REVIEW

**Comment by PocketMiner92** [comment]
Why only the shard?

**Comment by PocketMiner92** [comment]
copper_ingot 504:0
small_amethyst_bud 587:0
medium_amethyst_bud 586:0
large_amethyst_bud 585:0
amethyst_cluster 584:0
amethyst_block 582:0
amethyst_shard 625:0
sculk_sensor 562:0
sculk_catalyst 715:0
sculk_vein 714:0
sculk_shrieker 716:0
sculk 713:0
spyglass is now 626:0

**Comment by GoodLucky777** [comment]
I didn't add experimental things and copper ingot legacy numeric id is already used by disc. Also, Minecraft Wiki id is weird, too. (https://minecraft.fandom.com/wiki/Bedrock_Edition_data_values#Item_IDs and https://minecraft.fandom.com/wiki/Copper_Ingot#ID)

**Comment by PocketMiner92** [comment]
Ah ok i understand.

**Comment by GoodLucky777** [comment]
Maybe the IDs written in the individual item document have been changed to Numeric Runtime ID

**Review by PocketMiner92 — APPROVED** [review]

**Review by roridev — APPROVED** [review]

**Review by roridev — APPROVED** [review]

**Review by roridev — APPROVED** [review]

**Pull request merged**
