### PR TITLE
Implement `Block.onEntityStep(Entity)` to improve how cactus and magma blocks check if an entity is standing

### LINKED ISSUE #531: Magma block bug
# 🐞 I found a bug
Damages without touching the magma block

### 📸 Screenshots / Videos
Screenshot_20200829-211544

### 📋 Debug information
* Debug link: https://hastebin.com/ubuqerexej

### LINKED ISSUE #534: Cactus does not give damage on top
# 🐞 I found a bug

### 📸 Screenshots / Videos

https://imgur.com/a/jTpNZxT

### ▶ Steps to Reproduce

1. Put a Cactus
2. Stay on the top of the cactus.

### ✔ Expected Behavior

Give damage on top.

### ❌ Actual Behavior

Does nothing.

### 📋 Debug information

* PowerNukkit version: ✍ 1.3.1.4-PN
* Debug link: ✍ Does not working
* Timings link (if relevant): ✍

### PR DESCRIPTION
**Pull request by GoodLucky777**
Implement `Block.onEntityStep(Entity)` to improve how cactus and magma blocks check if an entity is standing (Fix #534), remove `BlockMagma.onEntityCollide(Entity)` because it is replaced with `BlockMagma.onEntityStep(Entity)` (Fix #531), change `BlockMagmaTest` because `BlockMagma.onEntityCollide(Entity)` is replaced with new method, and fix resistance of the cactus and magma block

### CODE REVIEW

**Review by LoboMetalurgico — CHANGES_REQUESTED** [review]
Hello, thanks for your Pull Request.

Unfortunately your correction was not effective, and we can still stand on top of the cactus. If you can fix it, I'll be happy to merge it.

**Comment by GoodLucky777** [comment]
> Hello, thanks for your Pull Request.
> 
> Unfortunately your correction was not effective, and we can still stand on top of the cactus. If you can fix it, I'll be happy to merge it.

Sorry, but I can't reproduce it. How can I reproduce it?
https://streamable.com/ys6wlp

**Comment by LoboMetalurgico** [comment]
This is weird... I replicated this exact situation in my test and the character took no damage.

**Comment by LoboMetalurgico** [comment]
I tested it by running PowerNukkit on my Linux computer and Minecraft 1.19.0 on my Android phone, I took damage on all sides, however, staying in the center on top of the cactus doesn't give me any damage.

I couldn't record the screen to show you, but unfortunately I couldn't replicate the success you had in your test.

**Comment by GoodLucky777** [comment]
I made a new check for this, is this working well?

**Comment by LoboMetalurgico** [comment]
Tests are failing. Could you check?

**Comment by GoodLucky777** [comment]
> Tests are failing. Could you check?

I fixed it

**Comment by GoodLucky777** [comment]
Closing this PR because PN is no longer maintained.

**Pull request closed without merging**
