### PR TITLE
Fix creation of anvil world format block entities

### PR DESCRIPTION
**Pull request by KCodeYT**

### CODE REVIEW

**Review by joserobjr — CHANGES_REQUESTED** [review]
Can you give us more details about the issue?

In Bedrock Edition block entities save ids don't follow `minecraft:snake_case` convention, it uses `CamelCase` without namespaces, as visible in https://minecraft.gamepedia.com/Brewing_Stand#ID
image

image

So `createBlockEntity` must accept only this format. And, the way you implemented the search for a case-insensitive key is not optimal.

We could make `createBlockEntity` accept case-insensitive types, but we can't make it accept types with namespace and underscores, they must be removed by the caller side when needed.

**Comment by KCodeYT** [comment]
In Bedrock Edition we use leveldb.

**Comment by KCodeYT** [comment]
But here we go, we use a modified version of anvil, so we have to support the Java Edition standards and not the Bedrock ones.

**Comment by KCodeYT** [comment]
And im closing this as anvil worlds, just create errors and should not be supported, we have to create our own world format which can only load bedrock levels

**Pull request closed without merging**
