### PR TITLE
Fixed #343 (Cancelling the InventoryTransactionEvent (on SlotChange) doesn't work correctly.)

### LINKED ISSUE #343: Cancelling the InventoryTransactionEvent (on SlotChange) doesn't work correctly.
# 🐞 I found a bug
I'm using FakeInventories, cancelling the event worked before 1.16. ~~Maybe FakeInventories issue, idk.~~ Nope, no FakeInventory issue. Also happens when cancelling "normal" InventoryTransactionEvent, e.g. EnderChest SlotChange.

### 📸 Screenshots / Videos
https://advancedcraft.net/vid/Bug_SlotChange.mp4

### ▶ Steps to Reproduce
Create a FakeInventory, cancel the FakeSlotChangeEvent.
Edit: Or just cancel the InventoryTransactionEvent.

### ✔ Expected Behavior
The item should also get deleted from the mouse.

### ❌ Actual Behavior
The Item is still in at the mouse.

### PR DESCRIPTION
**Pull request by PocketMiner82**
This fixed the bug, that cancelling the InventoryTransaction wouldn't update player's cursor inventory.

### CODE REVIEW

**Comment by PocketMiner82** [comment]
Seems like I made sth. wrong, don't merge!

**Comment by PocketMiner82** [comment]
Forgot to import classes... -_-

**Comment by PocketMiner82** [comment]
And found another bug: using shift to get out items now duplicates the item xD

**Comment by PocketMiner82** [comment]
I think, it can be merged now.

**Comment by PocketMiner82** [comment]
@joserobjr

**Comment by joserobjr** [comment]
I'm going to do a few tests before because it's a sensitive topic.

**Comment by PocketMiner82** [comment]
Found bug, currently trying to fix it.

**Comment by PocketMiner82** [comment]
Ok, was a bug in my plugin, the code here seems to be correct.

**Comment by PocketMiner82** [comment]
Hm... Sometimes, it works and sometimes it doesn't... Weird...

**Comment by PocketMiner82** [comment]
I think all issues are related to Inventory#sendContents...

**Comment by PocketMiner82** [comment]
@joserobjr I think, I have to close this, as I don't know, where the bug is from, because calling sendInventories in InventoryTransaction should work, but it doesn't... The inventory list inside this class contains all the inventories, that must be updated, but they don't update, idk why.

**Comment by PocketMiner82** [comment]
The method to update the invs is this:
2020-07-10_17h08_26

And my debug output is this, but the inv doesn't update:
2020-07-10_17h09_19

**Comment by PocketMiner82** [comment]
If the chest is DoubleChestFakeInventory, then sendContents works.

**Comment by PocketMiner82** [comment]
Something is wrong with this code:
```java
public void sendContents(Player... target) {
        InventoryContentPacket pk = new InventoryContentPacket();
        pk.slots = new Item[this.getSize()];
        for (int i = 0; i < this.getSize(); ++i) {
            pk.slots[i] = this.getItem(i);
        }

        for (Player p : target) {
            if (p == this.getHolder()) {
                pk.inventoryId = ContainerIds.UI;
                p.dataPacket(pk);
            } else {
                int id;

                if ((id = p.getWindowId(this)) == ContainerIds.NONE) {
                    System.out.println("sending not packet...");
                    this.close(p);
                    continue;
                }
                pk.inventoryId = id;

                p.dataPacket(pk);
            }
            System.out.println("sending packet...");
        }
    }
```

**Comment by PocketMiner82** [comment]
Maybe bug in my Plugin, currently testing...

**Comment by PocketMiner82** [comment]
Ok, was again issue in my plugin (and a bit in pn too xd) the following update should work.

**Comment by PocketMiner82** [comment]
I think, this was already fixed in https://github.com/CloudburstMC/Nukkit/commits/feature/1.16 in the latest commits. @joserobjr you can close this, if you want and merge the commits.

**Comment by PocketMiner82** [comment]
Closed. Reason: Was fixed with https://github.com/CloudburstMC/Nukkit/commit/3529299dd9cc21f6616794d8c6431457b5bcdde7.

**Comment by joserobjr** [comment]
Superseded by #384

**Pull request closed without merging**
