### PR TITLE
[WIP] Command Blocks and Minecart with Command Block Implementation with functionality

### PR DESCRIPTION
**Pull request by GoodLucky777**
Implement Command Blocks and Minecart with Command Block with functionality.

Add features from https://github.com/PowerNukkit/PowerNukkit/issues/122.

Block:
- [x] Implement Block without command functionality
- [x] Implement Repeating Command Block without command functionality
- [x] Implement Chain Command Block without command functionality

Entity:
- [x] Implement Minecart with Command Block without command functionality

TODO:
- [x] Fix Command Block Placement Rule

Functionality:
- [x] Command Block
- [x] Repeating Command Block
- [x] Chain Command Block
- [ ] Minecart with Command Block

TODO:
- [x] Fix Command Blocks are not saving some nbt
- [ ] Fix BlockEntityDataPacket is incorrect
- [x] Use New Block Entity Method
- [x] Use Block State
- [ ] Optimize Codes

### CODE REVIEW

**Comment by tuilakhanh** [comment]
Functionality but need to test

https://github.com/tuilakhanh/PowerNukkit/tree/add-command-block-without-functionality

**Comment by good777LUCKY** [comment]
> Functionality but need to test
> 
> https://github.com/tuilakhanh/PowerNukkit/tree/add-command-block-without-functionality

Can I merge with to this Pull Request?

**Comment by tuilakhanh** [comment]
> > Functionality but need to test
> > https://github.com/tuilakhanh/PowerNukkit/tree/add-command-block-without-functionality
> 
> Can I merge to this Pull Request?

if you want

I just ported it from the vanilacommandblock plugin. There is a lot of unsafe code that needs to be optimized

**Comment by good777LUCKY** [comment]
```[SERVER BOUND]  -  CommandBlockUpdatePacket(block=true, blockPosition=(221, 67, 113), mode=NORMAL, redstoneMode=false, conditional=false, minecartRuntimeEntityId=0, command=jejejwjw2j2j, lastOutput=, name=ekwmwmj, outputTracked=true, tickDelay=19, executingOnFirstTick=false)```
was correct but 
```[CLIENT BOUND]  -  BlockEntityDataPacket(blockPosition=(221, 67, 113), data={ 
  "conditionalMode": 0b,
  "auto": 0b,
  "LPRedstoneMode": 1b,
  "LastExecution": 0l,
  "LPCondionalMode": 1b,
  "SuccessCount": 0i,
  "LastOutputParams": [],
  "conditionMet": 0b,
  "Version": 10i,
  "ExecuteOnFirstTick": 0b,
  "x": 221i,
  "y": 67i,
  "z": 113i,
  "id": "CommandBlock",
  "TickDelay": 0i,
  "LPCommandMode": 0i,
  "TrackOutput": 1b
})```

**Comment by joserobjr** [comment]
Ignore the docker failed status

**Comment by PocketMiner82** [comment]
@good777LUCKY maybe you should look in GeyserMC for the packet thing, it's implemented there, idk

**Comment by GoodLucky777** [comment]
This pull request is outdated and broken. So I will close this, then open better one.

**Pull request closed without merging**
