### PR TITLE
Merge bleeding into mc-1.17/features

### PR DESCRIPTION
**Pull request by FlamingKnight**
This PR merges bleeding into mc-1.17/features, I decided to make a PR here instead of after I started to work on 1.17 stuff since there are a lot of changes to other files, most of them are small things such as the @PowerNukkitOnly annotation

### CODE REVIEW

**Comment by FlamingKnight** [comment]
The errors under the Maven build/check are related to testing, they just say that some creative items can't be registered such as Copper, Amethyst, and a few others which makes sense since they were never registered in the Block and Item classes

**Comment by PocketMiner92** [comment]
Powernukkit is inactive.
Many Users wait More then 2 Months of Fixes.
And nothing happens.

**Comment by YaNIND** [comment]
> Now the Last 1.17 IDS was released
> 
> copper_ingot 504:0 small_amethyst_bud 587:0 medium_amethyst_bud 586:0 large_amethyst_bud 585:0 amethyst_cluster 584:0 amethyst_block 582:0 amethyst_shard 625:0 sculk_sensor 562:0 sculk_catalyst 715:0 sculk_vein 714:0 sculk_shrieker 716:0 sculk 713:0 spyglass is now 626:0
> 
> @FlamingKnight @LoboMetalurgico @Gabriel8579

where you got thats IDs

**Comment by alikindsys** [comment]
Although I understand the reasoning behind merging `bleeding` onto `mc-1.17/features` this is clearly not the way to do this, since `mc-1.17/features` is the feature branch that will be merged into `bleeding`.

Also, you shouldn't base your work from any branch but `bleeding`, as per [contribution guidelines](https://github.com/PowerNukkit/PowerNukkit/blob/master/CONTRIBUTING.md). 

If you had any work lost on the middle of the 185 commits please split them into separate feature branches and re-submit them as separate PRs.

**Pull request closed without merging**
