### PR TITLE
Crimson/Warped Blocks Implementation

### PR DESCRIPTION
**Pull request by joserobjr**
This is a continuation of #327

REVIEW:
- [x] Crimson/Warped Stem
- [x] Crimson/Warped Stripped Stem
- [x] Crimson/Warped Hyphae
- [x] Crimson/Warped Stripped Hyphae
- [x] Crimson/Warped Planks
- [x] Crimson/Warped Door
- [x] Crimson/Warped Trapdoor
- [x] Crimson/Warped Fence
- [x] Crimson/Warped Fence Gate
- [x] Crimson/Warped Button
- [x] Crimson/Warped Pressure Plate
- [x] Crimson/Warped Sign Post
- [x] Crimson/Warped Wall Sign
- [x] Crimson/Warped Stairs
- [x] Crimson/Warped Slap
- [x] Crimson/Warped Double Slaps

TODO:
- [x] Review the blocks and make use of the block property api
- [x] Add all blocks color
- [x] Correct all resistance
- [x] Add correct face(damage) to stem
- [x] Add correct damage to hyphae
- [x] Warped/Crimson Nylium 
- [x] Warped/Crimson Roots
- [x] Warped/Crimson Fungus
- [X] Warped Wart Block
- [x] Shroomlight
- [x] Nether Sprouts
- [ ] Twisting/Weeping Vines
- [ ] Huge Warped/Crimson Fungus

TEST (place, break-time, drop, creative-pick):
- [x] Crimson/Warped Stem
- [x] Crimson/Warped Stripped Stem
- [x] Crimson/Warped Hyphae
- [x] Crimson/Warped Stripped Hyphae
- [x] Crimson/Warped Planks
- [x] Crimson/Warped Door
- [x] Crimson/Warped Trapdoor
- [x] Crimson/Warped Fence
- [x] Crimson/Warped Fence Gate
- [x] Crimson/Warped Button
- [x] Crimson/Warped Pressure Plate
- [x] Crimson/Warped Sign Post
- [x] Crimson/Warped Wall Sign
- [x] Crimson/Warped Stairs
- [x] Crimson/Warped Slap
- [X] Crimson/Warped Double Slaps

FIX:
- [x] Crimson/Warped Double Slaps are dropping as a single double slab block instead of two slabs.

### CODE REVIEW

**Comment by Gabriel8579** [comment]
I will help to test this

**Comment by Gabriel8579** [comment]
Was Warped/Crimson Nylium implemented?

**Comment by Gabriel8579** [comment]
image
I did it using all the blocks listed, time to test the break time. The creative-pick is working on all of them :)

**Comment by Gabriel8579** [comment]
Warped/Crimson Double Slabs is dropping a block

https://youtu.be/kuniI1tNOBg

**Comment by Gabriel8579** [comment]
> Warped/Crimson Double Slabs is dropping a block
> 
> https://youtu.be/kuniI1tNOBg

Except for that, everything looks good to me

**Comment by joserobjr** [comment]
Thank you. I added that them to the list 👍

**Comment by joserobjr** [comment]
Twisting/Weeping Vines
 Huge Warped/Crimson Fungus

Will be handled in an other PR

**Pull request merged**
