### PR TITLE
Add support to Minecraft 1.18.30

### PR DESCRIPTION
**Pull request by joserobjr**

### CODE REVIEW

**Comment by PleaseInsertNameHere** [comment]
ItemID Dupe - 634

**Comment by joserobjr** [comment]
> ItemID Dupe - 634 (runtime_item_states.json)

Can you link the lines? I can't find the dupe.

**Comment by PleaseInsertNameHere** [comment]
> > ItemID Dupe - 634 (runtime_item_states.json)
> 
> Can you link the lines? I can't find the dupe.

Sorry, mistake.

**Comment by joserobjr** [comment]
> > > ItemID Dupe - 634 (runtime_item_states.json)
> > 
> > 
> > Can you link the lines? I can't find the dupe.
> 
> Sorry, mistake.

No problem :)

**Comment by joserobjr** [comment]
> SonarCloud Quality Gate failed.    [Quality Gate failed](https://sonarcloud.io/dashboard?id=PowerNukkit_PowerNukkit&pullRequest=1338)
> 
> [Bug](https://sonarcloud.io/project/issues?id=PowerNukkit_PowerNukkit&pullRequest=1338&resolved=false&types=BUG) [A](https://sonarcloud.io/project/issues?id=PowerNukkit_PowerNukkit&pullRequest=1338&resolved=false&types=BUG) [0 Bugs](https://sonarcloud.io/project/issues?id=PowerNukkit_PowerNukkit&pullRequest=1338&resolved=false&types=BUG) [Vulnerability](https://sonarcloud.io/project/issues?id=PowerNukkit_PowerNukkit&pullRequest=1338&resolved=false&types=VULNERABILITY) [A](https://sonarcloud.io/project/issues?id=PowerNukkit_PowerNukkit&pullRequest=1338&resolved=false&types=VULNERABILITY) [0 Vulnerabilities](https://sonarcloud.io/project/issues?id=PowerNukkit_PowerNukkit&pullRequest=1338&resolved=false&types=VULNERABILITY) [Security Hotspot](https://sonarcloud.io/project/security_hotspots?id=PowerNukkit_PowerNukkit&pullRequest=1338&resolved=false&types=SECURITY_HOTSPOT) [A](https://sonarcloud.io/project/security_hotspots?id=PowerNukkit_PowerNukkit&pullRequest=1338&resolved=false&types=SECURITY_HOTSPOT) [0 Security Hotspots](https://sonarcloud.io/project/security_hotspots?id=PowerNukkit_PowerNukkit&pullRequest=1338&resolved=false&types=SECURITY_HOTSPOT) [Code Smell](https://sonarcloud.io/project/issues?id=PowerNukkit_PowerNukkit&pullRequest=1338&resolved=false&types=CODE_SMELL) [A](https://sonarcloud.io/project/issues?id=PowerNukkit_PowerNukkit&pullRequest=1338&resolved=false&types=CODE_SMELL) [12 Code Smells](https://sonarcloud.io/project/issues?id=PowerNukkit_PowerNukkit&pullRequest=1338&resolved=false&types=CODE_SMELL)
> 
> [](https://sonarcloud.io/component_measures?id=PowerNukkit_PowerNukkit&pullRequest=1338&metric=new_coverage&view=list) [25.3% Coverage](https://sonarcloud.io/component_measures?id=PowerNukkit_PowerNukkit&pullRequest=1338&metric=new_coverage&view=list) [](https://sonarcloud.io/component_measures?id=PowerNukkit_PowerNukkit&pullRequest=1338&metric=new_duplicated_lines_density&view=list) [0.0% Duplication](https://sonarcloud.io/component_measures?id=PowerNukkit_PowerNukkit&pullRequest=1338&metric=new_duplicated_lines_density&view=list)

Coverage will be skipped because this is an urgent update.

**Pull request merged**
