### PR TITLE
Update boats and minecarts

### PR DESCRIPTION
**Pull request by GoodLucky777**
Update boats and minecarts
- Entity
  - Keep custom name when boat drops
  - Keep custom name when minecart drops
  - Fix Minecart with TNT drops
- Item
  - Boat and Minecart will put CustomName to Entity if it have a custom name

### CODE REVIEW

**Review by Polyana-Fontes — DISMISSED** [review]
Thank you for the PR! 👍

**Review by Polyana-Fontes — DISMISSED** [review]

**Comment by roridev** [comment]
Why is this marked as *resolved* and the pr is open?

**Comment by GoodLucky777** [comment]
Ready to be reviewed

**Review by PocketMiner92 — APPROVED** [review]
♥️🥳

**Comment by GoodLucky777** [comment]
Closing this PR because PN is no longer maintained.

**Pull request closed without merging**
