### PR TITLE
Fix totem bug

### LINKED ISSUE #517: Bug for TOTEM
# 🐞 I found a bug

Totem does not save from everything

### ✔ Expected Behavior

If you burn in any way with a totem, then it will save you

### ❌ Actual Behavior

If you burn in any way with a totem, then it will not save you

### 📋 Debug information

* PowerNukkit version: ✍PowerNukkit v1.3.1.4-PN

### PR DESCRIPTION
**Pull request by Jl1mbo**
Fix #517 and #86

### CODE REVIEW

**Comment by joserobjr** [comment]
How can I reproduce the issue? In which way did you die while holding a totem?

The issues that you have linked are already marked as resolved.

**Comment by Jl1mbo** [comment]
I am using the most recent version of PowerNukkit and this issue has not been resolved.  To reproduce it, it is enough to die just from lava or a potion of instant damage, also from hunger

**Comment by joserobjr** [comment]
Can you share the URL which is generated at `/debugpaste upload`?

I just tried with fall damage, lava, and potion of instant damage and the totem has saved me

**Comment by Jl1mbo** [comment]
https://debugpaste.powernukkit.org/pastes/PN366a5358/

**Comment by Jl1mbo** [comment]
https://debugpaste.powernukkit.org/pastes/PN366a5358/

**Comment by joserobjr** [comment]
Can you check if this is still happening with you on the last successful build of 1.4.0.0-PN-SNAPSHOT?

Direct link: https://builds.powernukkit.org/repository/download/PowerNukkit_14/.lastSuccessful/powernukkit-1.4.0.0-PN-SNAPSHOT-shaded.jar
Build log: https://builds.powernukkit.org/buildConfiguration/PowerNukkit_14

**Comment by Jl1mbo** [comment]
> Can you check if this is still happening with you on the last successful build of 1.4.0.0-PN-SNAPSHOT?
> 
> Direct link: https://builds.powernukkit.org/repository/download/PowerNukkit_14/.lastSuccessful/powernukkit-1.4.0.0-PN-SNAPSHOT-shaded.jar (works with `wget`, `curl`, etc)
> Build log: https://builds.powernukkit.org/buildConfiguration/PowerNukkit_14
>

**Comment by tuilakhanh** [comment]
Fixed at #569

**Comment by joserobjr** [comment]
I noticed you have 3 plugins, maybe it's an incompatibility. Can you check if that happens without them?
```
plugins:
  PowerNukkit:
    version: '1.4.0.0-PN-SNAPSHOT'
    enabled: true
  DbLib:
    version: '1.0.1'
    enabled: true
  MobPlugin:
    version: '1.18.3.3'
    enabled: true
  AnarchyCore:
    version: '1.3'
    enabled: true
```

If it does, can you describe step-by-step the way to reproduce? Or what I am doing differently?
https://youtu.be/OmxvRaSn1VA

**Comment by Jl1mbo** [comment]
> > Can you check if this is still happening with you on the last successful build of 1.4.0.0-PN-SNAPSHOT?
> > 
> > Direct link: https://builds.powernukkit.org/repository/download/PowerNukkit_14/.lastSuccessful/powernukkit-1.4.0.0-PN-SNAPSHOT-shaded.jar (works with `wget`, `curl`, etc)
> > Build log: https://builds.powernukkit.org/buildConfiguration/PowerNukkit_14
> > 
> 
> 

This is what I tested WITHOUT plugins

**Comment by hteppl** [comment]
haha

**Pull request closed without merging**
