### PR TITLE
Fix stonecutter quick craft.

### PR DESCRIPTION
**Pull request by Extollite**

### CODE REVIEW

**Comment by joserobjr** [comment]
Hi @Extollite thank you for your PR!

But, what wasn't working? :P

**Comment by Extollite** [comment]
> Hi @Extollite thank you for your PR!
> 
> But, what wasn't working? :P

```
Error whilst processing the packet 30:InventoryTransactionPacket for santyelcrack180 (full data: InventoryTransactionPacket(transactionType=0, actions=[NetworkInventoryAction(sourceType=99999, windowId=-5, unknown=0, inventorySlot=0, oldItem=Item Diorite Slab (-162:4)x2, newItem=Item Air (0:0)x0, stackNetworkId=0), NetworkInventoryAction(sourceType=0, windowId=0, unknown=0, inventorySlot=2, oldItem=Item Diorite Slab (-162:4)x14, newItem=Item Diorite Slab (-162:4)x16, stackNetworkId=0)], transactionData=null, hasNetworkIds=false, legacyRequestId=0, isCraftingPart=true, isEnchantingPart=false))
java.lang.RuntimeException: Output list is full can't add Item Diorite Slab (-162:4)x2
at cn.nukkit.inventory.transaction.CraftingTransaction.setExtraOutput(CraftingTransaction.java:81) ~[server.jar:?]
at cn.nukkit.inventory.transaction.action.CraftingTransferMaterialAction.onAddToTransaction(CraftingTransferMaterialAction.java:27) ~[server.jar:?]
at cn.nukkit.inventory.transaction.InventoryTransaction.addAction(InventoryTransaction.java:99) ~[server.jar:?]
at cn.nukkit.Player.handleDataPacket(Player.java:3166) ~[server.jar:?]
at cn.nukkit.network.Network.lambda$processPackets$3(Network.java:285) ~[server.jar:?]
at java.util.ArrayList.forEach(ArrayList.java:1259) [?:1.8.0_262]
at cn.nukkit.network.Network.processPackets(Network.java:283) [server.jar:?]
at cn.nukkit.network.Network.processBatch(Network.java:269) [server.jar:?]
at cn.nukkit.Player.handleDataPacket(Player.java:2202) [server.jar:?]
at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:75) [server.jar:?]
at cn.nukkit.network.Network.processInterfaces(Network.java:158) [server.jar:?]
at cn.nukkit.Server.tick(Server.java:1342) [server.jar:?]
at cn.nukkit.Server.tickProcessor(Server.java:1125) [server.jar:?]
at cn.nukkit.Server.start(Server.java:1093) [server.jar:?]
at cn.nukkit.Server.<init>(Server.java:749) [server.jar:?]
at cn.nukkit.Nukkit.main(Nukkit.java:120) [server.jar:?]
```

**Comment by joserobjr** [comment]
Do you know the steps to reproduce the exception? I'm trying a lot but it is not reproducing.

**Comment by Extollite** [comment]
It might be my misconception or some quick craft add-on.

**Pull request closed without merging**
