### PR TITLE
Add support for WaterdogPE xuid and IP

### PR DESCRIPTION
**Pull request by funniray**
This PR adds support for the `Waterdog_XUID` and `Waterdog_IP` fields in the ClientChainData when settings.waterdogpe is true. The functionality is similar to how Spigot deals with Bungeecord.

~~As there were changes to the `lang` folder, commit [`f6f851b`](https://github.com/funniray/Nukkit_Languages/commit/f6f851bf4f202b44a2c61eff29ff404596d7e204) would also need to be merged.~~ Shouldn't be needed for PowerNukkit

This is the same PR as [`CloudburstMC/Nukkit#1986`](https://github.com/CloudburstMC/Nukkit/pull/1986), just adapted to PowerNukkit.

### CODE REVIEW

**Comment by alikindsys** [comment]
Please open a pull request for [`f6f851b`](https://github.com/funniray/Nukkit_Languages/commit/f6f851bf4f202b44a2c61eff29ff404596d7e204) on https://github.com/PowerNukkit/PowerNukkit-Languages since that change is a requirement for this pull request

**Comment by funniray** [comment]
Sorry, didn't realize that languages were handled differently on power-nukkit vs cloudburst's nukkit. I've went ahead and just added the option to default-nukkit.yml instead.

**Comment by irrld** [comment]
I think it would look cleaner if you rename Waterdog_IP and Waterdog_XUID to waterdogIP and waterdogXUID

**Comment by LoboMetalurgico** [comment]
Hello, thanks for your Pull Request. Our team will make a small change to the isWaterdog function, where we will move it to the server class, so that we can expose it to the plugins.

You don't have to worry about anything and we thank you for making this implementation!

**Review by LoboMetalurgico — APPROVED** [review]
Thank You!

**Review by alikindsys — APPROVED** [review]

**Pull request merged**
