### PR TITLE
Optimize ArmorStand Code

### PR DESCRIPTION
**Pull request by tuilakhanh**

### CODE REVIEW

**Review by joserobjr — CHANGES_REQUESTED** [review]
Thank you for the PR, I think some parts still need to be improved, I'm going to do some adjustments in the next days before merging.

**Comment by joserobjr** [comment]
```java
[22:55:45 TRACE]: [CLIENT BOUND]  -   /127.0.0.1:19132: AddEntityPacket(attributes=[AttributeData(name=minecraft:luck, minimum=-1024.0, maximum=0.0, value=1024.0, defaultValue=0.0), AttributeData(name=minecraft:health, minimum=0.0, maximum=6.0, value=6.0, defaultValue=6.0), AttributeData(name=minecraft:absorption, minimum=0.0, maximum=0.0, value=16.0, defaultValue=0.0), AttributeData(name=minecraft:movement, minimum=0.0, maximum=0.7, value=3.4028235E38, defaultValue=0.7), AttributeData(name=minecraft:underwater_movement, minimum=0.0, maximum=0.02, value=3.4028235E38, defaultValue=0.02), AttributeData(name=minecraft:lava_movement, minimum=0.0, maximum=0.02, value=3.4028235E38, defaultValue=0.02)], metadata={FLAGS=EntityFlags(flags=[HAS_COLLISION, HAS_GRAVITY]), FLAGS_2=EntityFlags(flags=[HAS_COLLISION, HAS_GRAVITY]), HEALTH=1, VARIANT=0, COLOR=0, NAMETAG=, OWNER_EID=-1, TARGET_EID=0, AIR_SUPPLY=300, EFFECT_COLOR=0, EFFECT_AMBIENT=0, JUMP_DURATION=0, HURT_TIME=0, HURT_DIRECTION=1, CHARGE_AMOUNT=0, LEASH_HOLDER_EID=0, SCALE=1.0, HAS_NPC_COMPONENT=0, MAX_AIR_SUPPLY=300, MARK_VARIANT=0, CONTAINER_TYPE=0, CONTAINER_BASE_SIZE=0, CONTAINER_STRENGTH_MODIFIER=0, BOUNDING_BOX_WIDTH=0.5, BOUNDING_BOX_HEIGHT=1.975, RIDER_SEAT_POSITION=(0.0, 0.0, 0.0), RIDER_ROTATION_LOCKED=0, RIDER_MAX_ROTATION=0.0, RIDER_MIN_ROTATION=0.0, COMMAND_BLOCK_ENABLED=0, COMMAND_BLOCK_COMMAND=, COMMAND_BLOCK_LAST_OUTPUT=, COMMAND_BLOCK_TRACK_OUTPUT=1, CONTROLLING_RIDER_SEAT_INDEX=0, STRENGTH=0, MAX_STRENGTH=0, EVOKER_SPELL_COLOR=0, LIMITED_LIFE=-1, ARMOR_STAND_POSE_INDEX=0, NAMETAG_ALWAYS_SHOW=0, COLOR_2=0, EATING_COUNTER=0, TRADE_TIER=0, MAX_TRADE_TIER=0, TRADE_XP=0, SKIN_ID=0, COMMAND_BLOCK_TICK_DELAY=3, COMMAND_BLOCK_EXECUTE_ON_FIRST_TICK=1, AMBIENT_SOUND_INTERVAL=8.0, AMBIENT_SOUND_INTERVAL_RANGE=16.0, AMBIENT_SOUND_EVENT_NAME=ambient, FALL_DAMAGE_MULTIPLIER=1.0, CAN_RIDE_TARGET=0, LOW_TIER_CURED_TRADE_DISCOUNT=0, HIGH_TIER_CURED_TRADE_DISCOUNT=0, NEARBY_CURED_TRADE_DISCOUNT=0, NEARBY_CURED_DISCOUNT_TIME_STAMP=0, HITBOX={}, IS_BUOYANT=0}, entityLinks=[], uniqueEntityId=-77309411324, runtimeEntityId=6, identifier=minecraft:armor_stand, entityType=0, position=(548.5, 63.0, 15.5), motion=(0.0, -0.0784, 0.0), rotation=(0.0, -180.0, -180.0))
```

**Comment by joserobjr** [comment]
Hurt animation:
```java
[23:01:22 TRACE]: [SERVER BOUND]  -   /127.0.0.1:50936: AnimatePacket(rowingTime=0.0, action=SWING_ARM, runtimeEntityId=1)
[23:01:22 TRACE]: [SERVER BOUND]  -   /127.0.0.1:50936: AnimatePacket(rowingTime=0.0, action=SWING_ARM, runtimeEntityId=1)
[23:01:22 TRACE]: [SERVER BOUND]  -   /127.0.0.1:50936: LevelSoundEvent2Packet(sound=ATTACK_STRONG, position=(548.5, 63.9875, 15.5), extraData=-1, identifier=minecraft:player, babySound=false, relativeVolumeDisabled=false)
[23:01:22 TRACE]: [SERVER BOUND]  -   /127.0.0.1:50936: InventoryTransactionPacket(legacyRequestId=0, legacySlots=[], actions=[], transactionType=ITEM_USE_ON_ENTITY, actionType=1, runtimeEntityId=7, blockPosition=null, blockFace=0, hotbarSlot=8, itemInHand=ItemData(id=0, damage=0, count=0, tag=null, canPlace=[], canBreak=[], blockingTicks=0, netId=0), playerPosition=(548.5799, 64.62001, 14.209931), clickPosition=(0.0, 0.0, 0.0), headPosition=null, hasNetworkIds=false, blockRuntimeId=0)
[23:01:22 TRACE]: [CLIENT BOUND]  -   /127.0.0.1:19132: LevelSoundEvent2Packet(sound=ATTACK_STRONG, position=(548.5, 63.9875, 15.5), extraData=-1, identifier=minecraft:player, babySound=false, relativeVolumeDisabled=false)
[23:01:22 TRACE]: [CLIENT BOUND]  -   /127.0.0.1:19132: LevelSoundEvent2Packet(sound=ATTACK_STRONG, position=(548.5, 63.9875, 15.5), extraData=-1, identifier=minecraft:player, babySound=false, relativeVolumeDisabled=false)
[23:01:22 TRACE]: [CLIENT BOUND]  -   /127.0.0.1:19132: LevelEventPacket(type=SOUND_ARMOR_STAND_HIT, position=(548.5, 63.0, 15.5), data=0)
[23:01:22 TRACE]: [CLIENT BOUND]  -   /127.0.0.1:19132: SetEntityDataPacket(metadata={HEALTH=-10, HURT_TIME=9, HURT_DIRECTION=-1}, runtimeEntityId=7, tick=0)
[23:01:22 TRACE]: [CLIENT BOUND]  -   /127.0.0.1:19132: SetEntityDataPacket(metadata={HURT_TIME=8}, runtimeEntityId=7, tick=0)
[23:01:22 TRACE]: [SERVER BOUND]  -   /127.0.0.1:50936: InteractPacket(action=MOUSEOVER, runtimeEntityId=7, mousePosition=(548.5884, 64.334335, 15.15))
[23:01:22 TRACE]: [CLIENT BOUND]  -   /127.0.0.1:19132: SetEntityDataPacket(metadata={HURT_TIME=7}, runtimeEntityId=7, tick=0)
[23:01:22 TRACE]: [SERVER BOUND]  -   /127.0.0.1:50936: InteractPacket(action=MOUSEOVER, runtimeEntityId=7, mousePosition=(548.5884, 64.334335, 15.15))
[23:01:22 TRACE]: [CLIENT BOUND]  -   /127.0.0.1:19132: SetEntityDataPacket(metadata={HURT_TIME=6}, runtimeEntityId=7, tick=0)
[23:01:22 TRACE]: [SERVER BOUND]  -   /127.0.0.1:50936: InteractPacket(action=MOUSEOVER, runtimeEntityId=7, mousePosition=(548.5884, 64.334335, 15.15))
[23:01:22 TRACE]: [CLIENT BOUND]  -   /127.0.0.1:19132: SetEntityDataPacket(metadata={HURT_TIME=5}, runtimeEntityId=7, tick=0)
[23:01:22 TRACE]: [SERVER BOUND]  -   /127.0.0.1:50936: InteractPacket(action=MOUSEOVER, runtimeEntityId=7, mousePosition=(548.5884, 64.334335, 15.15))
[23:01:22 TRACE]: [CLIENT BOUND]  -   /127.0.0.1:19132: SetEntityDataPacket(metadata={HURT_TIME=4}, runtimeEntityId=7, tick=0)
[23:01:22 TRACE]: [SERVER BOUND]  -   /127.0.0.1:50936: InteractPacket(action=MOUSEOVER, runtimeEntityId=7, mousePosition=(548.5884, 64.334335, 15.15))
[23:01:22 TRACE]: [CLIENT BOUND]  -   /127.0.0.1:19132: SetEntityDataPacket(metadata={HURT_TIME=3}, runtimeEntityId=7, tick=0)
[23:01:22 TRACE]: [SERVER BOUND]  -   /127.0.0.1:50936: InteractPacket(action=MOUSEOVER, runtimeEntityId=7, mousePosition=(548.5884, 64.334335, 15.15))
[23:01:22 TRACE]: [CLIENT BOUND]  -   /127.0.0.1:19132: SetEntityDataPacket(metadata={HURT_TIME=2}, runtimeEntityId=7, tick=0)
[23:01:22 TRACE]: [SERVER BOUND]  -   /127.0.0.1:50936: InteractPacket(action=MOUSEOVER, runtimeEntityId=7, mousePosition=(548.5884, 64.334335, 15.15))
[23:01:22 TRACE]: [CLIENT BOUND]  -   /127.0.0.1:19132: SetEntityDataPacket(metadata={HURT_TIME=1}, runtimeEntityId=7, tick=0)
[23:01:22 TRACE]: [SERVER BOUND]  -   /127.0.0.1:50936: InteractPacket(action=MOUSEOVER, runtimeEntityId=7, mousePosition=(548.5884, 64.334335, 15.15))
[23:01:22 TRACE]: [CLIENT BOUND]  -   /127.0.0.1:19132: SetEntityDataPacket(metadata={HURT_TIME=0}, runtimeEntityId=7, tick=0)
[23:01:23 TRACE]: [SERVER BOUND]  -   /127.0.0.1:50936: InteractPacket(action=MOUSEOVER, runtimeEntityId=7, mousePosition=(548.5884, 64.334335, 15.15))
[23:01:23 TRACE]: [SERVER BOUND]  -   /127.0.0.1:50936: InteractPacket(action=MOUSEOVER, runtimeEntityId=7, mousePosition=(548.5884, 64.334335, 15.15))
```

**Review by joserobjr — DISMISSED** [review]
Thank you!

Since I also coded on this PR, I'm going to await another review to review before merging.

**Review by joserobjr — APPROVED** [review]

**Review by LoboMetalurgico — APPROVED** [review]

**Pull request merged**
