### PR TITLE
[WIP] Add BambooJungleBiome and BambooJungleHillsBiome

### PR DESCRIPTION
**Pull request by GoodLucky777**
Implement BambooJungleBiome and BambooJungleHillsBiome.

TODO:
- [x] Add BambooJungleBiome
- [x] Add BambooJungleHillsBiome
- [x] Add new biomes enums
- [x] Add PopulatorBamboo
- [x] Add to BiomeSelector
- [ ] Correct all populator values
- [ ] Check BambooJungleHillsBiome height values
- [ ] Check Podzol populator
- [ ] In BambooJungleBiome and BambooJungleHillsBiome, there is no small Oak tree
- [x] Correct Bamboo height Check
- [ ] Correct BiomeSelector
- [ ] Fix Bamboo have no leaves
- [ ] Optimize Codes

### CODE REVIEW

**Comment by joserobjr** [comment]
Hi, please merge our master branch into the master branch of your fork, it will fix the red X that are appearing in your commits. It's happening because there is a bug in the DockerCloud checking system that makes it fails to switch to the branch that is being used in the PR when there are files with wrong line break terminations in the master branch. We have already fixed it in our master.

**Comment by good777LUCKY** [comment]
> Hi, please merge our master branch into the master branch of your fork, it will fix the red X that are appearing in your commits. It's happening because there is a bug in the DockerCloud checking system that makes it fails to switch to the branch that is being used in the PR when there are files with wrong line break terminations in the master branch. We have already fixed it in our master.

When I try to merge PowerNukkit Master branch to my fork, it says it is already up to date.

**Comment by joserobjr** [comment]
> > Hi, please merge our master branch into the master branch of your fork, it will fix the red X that are appearing in your commits. It's happening because there is a bug in the DockerCloud checking system that makes it fails to switch to the branch that is being used in the PR when there are files with wrong line break terminations in the master branch. We have already fixed it in our master.
> 
> When I try to merge PowerNukkit Master branch to my fork, it says it is already up to date.

I opened it for you: https://github.com/good777LUCKY/PowerNukkit/pull/25

**Comment by good777LUCKY** [comment]
> > > Hi, please merge our master branch into the master branch of your fork, it will fix the red X that are appearing in your commits. It's happening because there is a bug in the DockerCloud checking system that makes it fails to switch to the branch that is being used in the PR when there are files with wrong line break terminations in the master branch. We have already fixed it in our master.
> > 
> > 
> > When I try to merge PowerNukkit Master branch to my fork, it says it is already up to date.
> 
> I opened it for you: [good777LUCKY#25](https://github.com/good777LUCKY/PowerNukkit/pull/25)

Oh I'm sorry, I thought I should merge Powernukkit master branch to add-biome-bamboo branch.

**Comment by GoodLucky777** [comment]
This pull request is outdated. So I will close this, then open better one.

**Pull request closed without merging**
