### PR TITLE
Migrating honey block to Nukkit 2.0

### PR DESCRIPTION
**Pull request by LoboMetalurgico**

### CODE REVIEW

**Comment by joserobjr** [comment]
Depends on NukkitX#1128 to work

**Comment by LoboMetalurgico** [comment]
Oh, Ok.

**Comment by joserobjr** [comment]
As a workaround, adds this to the server plugin folder:
https://github.com/GameModsBR/Workaround-NukkitX-1128/releases/tag/0.0.1

**Comment by joserobjr** [comment]
Dependency is resolved, I'm going to merge from NukkiX into here, please remove the temporary plugin from the plugins folder after you update your workspace.

**Pull request closed without merging**
