### PR TITLE
Bump protocol + Miscelaneous Fixes

### PR DESCRIPTION
**Pull request by Gabriel8579**

### CODE REVIEW

**Comment by PocketMiner92** [comment]
#1315
#1316
#1317

**Comment by Gabriel8579** [comment]
#1320 #1322

**Comment by roridev** [comment]
Can we confirm if this pull request works as expected? I'll later attempt to merge it using the cli and see if it requires code owner review.

**Comment by AlicanCopur** [comment]
We're using this branch on production (80-100 players) for 3 days and looks fine, but maybe it requires code owner review, i dont know.

**Comment by LoboMetalurgico** [comment]
> We're using this branch on production (80-100 players) for 3 days and looks fine, but maybe it requires code owner review, i dont know.

Require, unfortunally

**Comment by roridev** [comment]
> Can we confirm if this pull request works as expected? I'll later attempt to merge it using the cli and see if it requires code owner review.

I tried doing that but no, not even asking github directly would work. it **really** asks for @joserobjr's review. nothing we can do.
image
image

**Comment by RealTriassic** [comment]
> > We're using this branch on production (80-100 players) for 3 days and looks fine, but maybe it requires code owner review, i dont know.
> 
> Require, unfortunally

good luck have fun

**Comment by eat-sleep-code** [comment]
Seems like having a single code owner being able to review is a problem.   If he/she gets hit by the lotto bus, then this project repo is dead.   

I would suggest reviewing the "Require review from Code Owners"  checkbox if the Branch protection rule if there is only one code owner.   Otherwise, assign a secondary code owner.

**Comment by Gabriel8579** [comment]
> Seems like having a single code owner being able to review is a problem. If he/she gets hit by the lotto bus, then this project repo is dead.
> 
> I would suggest reviewing the "Require review from Code Owners" checkbox if the Branch protection rule if there is only one code owner. Otherwise, assign a secondary code owner.

Yes, usually the code owner is active, but there were some personal problems with him and he is incommunicable for now, we have to wait because no one is allowed to change this configuration except him. You can still download the build of this change from runs: https://github.com/PowerNukkit/PowerNukkit/actions/runs/1838944773

**Comment by PocketMiner92** [comment]
Jose is alive

**Pull request merged**
