### PR TITLE
Soul Lantern, Soul Torch, Chain Implementation

### PR DESCRIPTION
**Pull request by good777LUCKY**
- [x] Soul Lantern Implementation
 - ID: 524
 - Light Level: 10

- [x] Soul Torch Implementation
 - ID: 523
 - Light Level: 10

- [x] Chain Implementation
 - ID: 541 (Item ID: 758)
 - Blast resistance: 6
 - Hardness: 5
 - Tool: Any Pickaxe
 - Flamable: no
 - Water Flowable: yes
 - Block Color: BLACK

- [x] Chain Connection Implementation
  - Lanterns: Implemented
  - Bell: Implemented

### CODE REVIEW

**Comment by joserobjr** [comment]
Thank you! Changing the target branch, some hundred of commits might appear, ignore them. The branch is fine

**Comment by good777LUCKY** [comment]
Issue:
  - Fix that it becomes to Update Me! block.

**Comment by joserobjr** [comment]
Don't worry about that, its a block_states_override.dat mapping which was not done yet.

**Comment by good777LUCKY** [comment]
Oh thank you

**Comment by MrRazamataz** [comment]
image
The blocks implemented in the build/version turn into update blocks. IDK if this is known about or not but im letting you know.

**Comment by good777LUCKY** [comment]
> image
> The blocks implemented in the build/version turn into update blocks. IDK if this is known about or not but im letting you know.

Screenshot

**Comment by MrRazamataz** [comment]
I see. Ok. Thanks. Didnt see that before I must be blind.

**Comment by good777LUCKY** [comment]
`good777LUCKY removed their assignment now`
I accidentally remove it. Sorry.

**Comment by MrRazamataz** [comment]
It still times out when a new player joins. This is what happens. 
https://www.youtube.com/watch?v=Qe6A10G6htY&feature=youtu.be

**Comment by good777LUCKY** [comment]
> It still times out when a new player joins. This is what happens.
> https://www.youtube.com/watch?v=Qe6A10G6htY&feature=youtu.be

Can you try it with latest build?

**Comment by MrRazamataz** [comment]
Yes I will try it.

**Comment by good777LUCKY** [comment]
@joserobjr Is there something wrong with this pull request?

**Comment by zombihunterbonn** [comment]
Kolben broken to?

good777LUCKY <notifications@github.com> schrieb am Mi., 1. Juli 2020, 17:53:

**Comment by joserobjr** [comment]
@good777LUCKY I'm going to review in about 3 hours

**Comment by good777LUCKY** [comment]
> @good777LUCKY I'm going to review in about 3 hours

Does review finished?

**Comment by good777LUCKY** [comment]
> @good777LUCKY I'm going to review in about 3 hours

@joserobjr Does review finished?

**Comment by joserobjr** [comment]
@good777LUCKY it's depending on the `block_states_overrides.dat` update, I'm working on it

**Comment by good777LUCKY** [comment]
Thank you!

**Pull request merged**
