### PR TITLE
Update the resources

### PR DESCRIPTION
**Pull request by joserobjr**
Fixes some issues with creative inventory, prepare for the new biomes, fix Piglin Brute spawn egg being completely black, and missing in the creative inventory.

Also, fixes some crafting recipes.

### CODE REVIEW

**Comment by good777LUCKY** [comment]
Piglin brute spawn egg is working fine. (https://github.com/PowerNukkit/PowerNukkit/pull/604/commits/9cf4f24ed83ebd822fed5f18319e8cd0a5880328)

**Comment by good777LUCKY** [comment]
I forgot to say this. Some crafting recipe damage -1 have been changed to 32767. Also, error occur. (debug level)

**Comment by joserobjr** [comment]
`32767` is `-1` in short type. In our case it's safer to keep as `-1`.

```java
public class Main
{
	public static void main(String[] args) {
	    short s = -1;
	    int i = s;
	    int masked = s & 0xFFFF;
	    short overflowed = (short)masked;
	    System.out.println("s="+s+", i="+i+", masked="+masked+", overflowed="+overflowed);
	}
}
```
Result:
```
s=-1, i=-1, masked=65535, overflowed=-1 
```

https://onlinegdb.com/rySH0d-Hv

I can't reproduce the error. When the resources are changed we need to do a `mvn clean` once.

```java
Connected to the target VM, address: '127.0.0.1:53582', transport: 'socket'
21:26:02 [INFO ] Loading nukkit.yml ...
21:26:02 [INFO ] Loading server.properties ...
21:26:02 [INFO ] Selecionado Português (bra) como a linguagem base
21:26:02 [INFO ] Iniciando Servidor de Minecraft: BE, versão v1.16.20
21:26:02 [INFO ] Selected Zlib Provider: 2 (cn.nukkit.utils.ZlibThreadLocal)
21:26:02 [INFO ] Abrindo servidor em 0.0.0.0:19132
21:26:03 [INFO ] Este servidor está rodando Nukkit versão 1.4.0.0-PN-SNAPSHOT (git-ba97c59) "PowerNukkit" (API 1.0.11)
21:26:03 [INFO ] Nukkit é distribuído com a licença GPL
21:26:03 [DEBUG] Timings: 
Enabled - false
Verbose - false
History Interval - 6000
History Length - 72000
21:26:04 [INFO ] Loading recipes...
21:26:04 [INFO ] Loaded 1509 recipes.
21:26:04 [INFO ] Carregado com sucesso 0 pacotes de recurso
21:26:04 [DEBUG] -Dio.netty.eventLoopThreads: 32
21:26:04 [DEBUG] -Dio.netty.threadLocalMap.stringBuilder.initialSize: 1024
21:26:04 [DEBUG] -Dio.netty.threadLocalMap.stringBuilder.maxSize: 4096
21:26:04 [DEBUG] -Dio.netty.noKeySetOptimization: false
21:26:04 [DEBUG] -Dio.netty.selectorAutoRebuildThreshold: 512
21:26:04 [DEBUG] Platform: Windows
21:26:04 [DEBUG] -Dio.netty.noUnsafe: false
21:26:04 [DEBUG] Java version: 8
21:26:04 [DEBUG] sun.misc.Unsafe.theUnsafe: available
21:26:04 [DEBUG] sun.misc.Unsafe.copyMemory: available
21:26:04 [DEBUG] java.nio.Buffer.address: available
21:26:04 [DEBUG] direct buffer constructor: available
21:26:04 [DEBUG] java.nio.Bits.unaligned: available, true
21:26:04 [DEBUG] jdk.internal.misc.Unsafe.allocateUninitializedArray(int): unavailable prior to Java9
21:26:04 [DEBUG] java.nio.DirectByteBuffer.<init>(long, int): available
21:26:04 [DEBUG] sun.misc.Unsafe: available
21:26:04 [DEBUG] -Dio.netty.tmpdir: C:\Users\joser\AppData\Local\Temp (java.io.tmpdir)
21:26:04 [DEBUG] -Dio.netty.bitMode: 64 (sun.arch.data.model)
21:26:04 [DEBUG] -Dio.netty.maxDirectMemory: 5708447744 bytes
21:26:04 [DEBUG] -Dio.netty.uninitializedArrayAllocationThreshold: -1
21:26:04 [DEBUG] java.nio.ByteBuffer.cleaner(): available
21:26:04 [DEBUG] -Dio.netty.noPreferDirect: false
21:26:04 [DEBUG] org.jctools-core.MpscChunkedArrayQueue: available
21:26:04 [TRACE] instrumented a special java.util.Set into: sun.nio.ch.WindowsSelectorImpl@1c6c6f24
21:26:04 [TRACE] instrumented a special java.util.Set into: sun.nio.ch.WindowsSelectorImpl@6a48a7f3
21:26:04 [TRACE] instrumented a special java.util.Set into: sun.nio.ch.WindowsSelectorImpl@3f985a86
21:26:04 [TRACE] instrumented a special java.util.Set into: sun.nio.ch.WindowsSelectorImpl@57a2ed35
21:26:04 [TRACE] instrumented a special java.util.Set into: sun.nio.ch.WindowsSelectorImpl@12ffd1de
21:26:04 [TRACE] instrumented a special java.util.Set into: sun.nio.ch.WindowsSelectorImpl@3d278b4d
21:26:04 [TRACE] instrumented a special java.util.Set into: sun.nio.ch.WindowsSelectorImpl@4096aa05
21:26:04 [TRACE] instrumented a special java.util.Set into: sun.nio.ch.WindowsSelectorImpl@9d3c67
21:26:04 [TRACE] instrumented a special java.util.Set into: sun.nio.ch.WindowsSelectorImpl@6c806c8b
21:26:04 [TRACE] instrumented a special java.util.Set into: sun.nio.ch.WindowsSelectorImpl@6dfcffb5
21:26:04 [TRACE] instrumented a special java.util.Set into: sun.nio.ch.WindowsSelectorImpl@184fb68d
21:26:04 [TRACE] instrumented a special java.util.Set into: sun.nio.ch.WindowsSelectorImpl@71d8cfe7
21:26:04 [TRACE] instrumented a special java.util.Set into: sun.nio.ch.WindowsSelectorImpl@1e530163
21:26:04 [TRACE] instrumented a special java.util.Set into: sun.nio.ch.WindowsSelectorImpl@14d8444b
21:26:04 [TRACE] instrumented a special java.util.Set into: sun.nio.ch.WindowsSelectorImpl@71466383
21:26:04 [TRACE] instrumented a special java.util.Set into: sun.nio.ch.WindowsSelectorImpl@46d63dbb
21:26:04 [TRACE] instrumented a special java.util.Set into: sun.nio.ch.WindowsSelectorImpl@4088741b
21:26:04 [TRACE] instrumented a special java.util.Set into: sun.nio.ch.WindowsSelectorImpl@16a49a5d
21:26:04 [TRACE] instrumented a special java.util.Set into: sun.nio.ch.WindowsSelectorImpl@54bca971
21:26:04 [TRACE] instrumented a special java.util.Set into: sun.nio.ch.WindowsSelectorImpl@23706db8
21:26:04 [TRACE] instrumented a special java.util.Set into: sun.nio.ch.WindowsSelectorImpl@205bed61
21:26:04 [TRACE] instrumented a special java.util.Set into: sun.nio.ch.WindowsSelectorImpl@129fed45
21:26:04 [TRACE] instrumented a special java.util.Set into: sun.nio.ch.WindowsSelectorImpl@23592946
21:26:04 [TRACE] instrumented a special java.util.Set into: sun.nio.ch.WindowsSelectorImpl@3e48d38
21:26:04 [TRACE] instrumented a special java.util.Set into: sun.nio.ch.WindowsSelectorImpl@7c2b58c0
21:26:04 [TRACE] instrumented a special java.util.Set into: sun.nio.ch.WindowsSelectorImpl@11b377c5
21:26:04 [TRACE] instrumented a special java.util.Set into: sun.nio.ch.WindowsSelectorImpl@7bca6fac
21:26:04 [TRACE] instrumented a special java.util.Set into: sun.nio.ch.WindowsSelectorImpl@5c60b0a0
21:26:04 [TRACE] instrumented a special java.util.Set into: sun.nio.ch.WindowsSelectorImpl@7a2b1eb4
21:26:04 [TRACE] instrumented a special java.util.Set into: sun.nio.ch.WindowsSelectorImpl@702c436b
21:26:04 [TRACE] instrumented a special java.util.Set into: sun.nio.ch.WindowsSelectorImpl@5833f5cd
21:26:04 [TRACE] instrumented a special java.util.Set into: sun.nio.ch.WindowsSelectorImpl@10fbbdb
21:26:04 [DEBUG] -Dio.netty.allocator.type: unpooled
21:26:04 [DEBUG] -Dio.netty.threadLocalDirectBufferSize: 0
21:26:04 [DEBUG] -Dio.netty.maxThreadLocalCharBufferSize: 16384
21:26:04 [DEBUG] -Dio.netty.processId: 19656 (auto-detected)
21:26:04 [DEBUG] -Djava.net.preferIPv4Stack: true
21:26:04 [DEBUG] -Djava.net.preferIPv6Addresses: false
21:26:04 [DEBUG] Loopback interface: lo (Software Loopback Interface 1, 127.0.0.1)
21:26:04 [DEBUG] Failed to get SOMAXCONN from sysctl and file \proc\sys\net\core\somaxconn. Default: 200
21:26:05 [DEBUG] -Dio.netty.machineId: 70:85:c2:ff:fe:d0:13:27 (auto-detected)
21:26:05 [DEBUG] Loading position tracking service
21:26:05 [INFO ] Ativando PowerNukkit v1.4.0.0-PN-SNAPSHOT
21:26:05 [INFO ] Carregando GetId v1.0.0
21:26:05 [INFO ] Carregando ChemistryGameplay v1.1.388
21:26:05 [INFO ] Preparando mundo "world"
21:26:05 [WARN ] No level called "nether" found or nether is disabled in server properties! Nether functionality will be disabled.
21:26:05 [INFO ] Ativando GetId v1.0.0
21:26:05 [INFO ] Ativando ChemistryGameplay v1.1.388
21:26:05 [INFO ] Iniciando listener de status GS4
21:26:05 [INFO ] Porta de query está ativada em 19132
21:26:05 [INFO ] Query executando em 0.0.0.0:19132
21:26:05 [INFO ] Modo de jogo padrão: Modo Sobrevivência
21:26:05 [INFO ] Finalizado (2.433s)! Para ver a ajuda, escreva "help" ou "?"
> 
```

**Comment by joserobjr** [comment]
I just realized the `masked=65535`, ok 65535 is -1, and 32767 is Short.MAX. But still, they want to indicate that that damage value is irrelevant (fuzzy), changing to Short.MAX could cause breaking changes, it's still safer to keep as -1.

**Pull request merged**
