### PR TITLE
Add option that set players skin trusted

### PR DESCRIPTION
**Pull request by good777LUCKY**
Add option that set players skin trusted.

If you enable this option in `nukkit.yml` (force-skin-trusted), every player skin will be trusted. (It doesn't affect when you change player's skin with plugin. It only affect login packet and player skin packet in cn.nukkit.Player.)

### CODE REVIEW

**Comment by joserobjr** [comment]
Hi, what would be the benefit of force-trusting all skins?

**Comment by joserobjr** [comment]
Oh My God! You solved the mystery! I was going crazy while I was trying to understand why the /cloneme command from the example plugins wasn't showing some player skins in the clones!

https://www.reddit.com/r/MinecraftHelp/comments/hk5ok3/bedrock_only_allow_trusted_skins/

**Comment by good777LUCKY** [comment]
> Hi, what would be the benefit of force-trusting all skins?

It will be useful and easy way to do it for the server that want to show all skins made by players.

**Review by joserobjr — APPROVED** [review]
Thank you 👍

**Pull request merged**
