### PR TITLE
Add support for the Minecraft 1.17.30 protocol(465)

### PR DESCRIPTION
**Pull request by joserobjr**
This is the follow-up of #1231

This PR allows me to update the dumps, annotations, etc, before merging into bleeding.

### CODE REVIEW

**Comment by PleaseInsertNameHere** [comment]
Redstone Repeater looks a bit weird in creative inventory when using this

**Comment by joserobjr** [comment]
> Redstone Repeater looks a bit weird in creative inventory when using this

@PleaseInsertNameHere looks normal to me, can you add a screenshot?
image

**Comment by PleaseInsertNameHere** [comment]
> > Redstone Repeater looks a bit weird in creative inventory when using this
> 
> @PleaseInsertNameHere looks normal to me, can you add a screenshot?
> image

There are these two:
image

**Review by joserobjr — COMMENTED** [review]
Looking good for me now

**Comment by joserobjr** [comment]
> > > Redstone Repeater looks a bit weird in creative inventory when using this
> > 
> > 
> > @PleaseInsertNameHere looks normal to me, can you add a screenshot?
> > image
> 
> There are these two:
> image

Thank you. I think it's fixed now.
image

**Pull request merged**
