### PR TITLE
Fix GlazedTerracotta moving

### PR DESCRIPTION
**Pull request by PocketMiner82**
- [X] Depends on #750 

- [X] Add behavior of GlazedTerracotta
- [X] Fix honey and slime connections again

### CODE REVIEW

**Comment by PocketMiner82** [comment]
(only last 2 commits)

**Comment by PocketMiner82** [comment]
I also added some java doc comments and normal comments to the BlockCalculator, because it is hard to understand what it does, if you don't read every single line -.-

**Comment by PocketMiner82** [comment]
I'll delete my account soon, as I want a new email and username.

If you want to keep my work in a PR I think you have to clone the branch to PN.

Thanks,
PocketMiner82

**Comment by LoboMetalurgico** [comment]
Moved to PullRequest #900

**Pull request closed without merging**
