### PR TITLE
Update StartGamePacket (protocol v527, v1.19.0)

### PR DESCRIPTION
**Pull request by GoodLucky777**
Update StartGamePacket (protocol v527, v1.19.0) and implement #938 partially

- StartGamePacket
  - Add ExperimentData, SyncedPlayerMovementSettings, BlockPropertyData, AuthoritativeMovementMode, EduSharedUriResource
  - Add educationProductionId, experiments, experimentsPreviouslyToggled, limitedWorldWidth, limitedWorldHeight, netherType, forceExperimentalGameplay, playerMovementSettings, properties, blockRegistryChecksum, seed64, eduSharedUriResource, worldTemplateId
  - Add default value to dayCycleStopTime, premiumWorldTemplateId, serverEngine

TODO:
- [x] 1.17 Update
- [x] 1.18 Update
- [x] 1.18.30 Update
- [x] 1.19.0 Update
- [ ] 1.19.10 Update
- [ ] 1.19.20 Update

Require:
- [x] #812 Merge
- [x] #1360 Merge
- [x] #1388 Merge
- [x] #1393 Merge

### CODE REVIEW

**Comment by LoboMetalurgico** [comment]
Hello! Can you update to protocol 475+?

**Comment by GoodLucky777** [comment]
> Hello! Can you update to protocol 475+?

Okay, I updated it

**Comment by LoboMetalurgico** [comment]
Hello, it's me again. Could you resolve the conflict in the file please? After that, I believe we will finally be able to merge into the main branch.

**Comment by roridev** [comment]
Seemed trivial, please check to see if it works.

**Comment by LoboMetalurgico** [comment]
> Seemed trivial, please check to see if it works.

My question with this merge is that maybe the changes could change something in the packet

**Comment by GoodLucky777** [comment]
Ready to be reviewed

**Review by alikindsys — DISMISSED** [review]

**Comment by GoodLucky777** [comment]
Ready to be reviewed

**Comment by GoodLucky777** [comment]
Closing this PR because PN is no longer maintained.

**Pull request closed without merging**
